apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: 'true'
  name: redis-slot1
  labels:
    name: redis-slot1
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-slot1
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: redis-slot1
  labels:
    name: redis-slot1       
spec:
  replicas: 2      
  selector:
    name: redis-slot1
  template:
    metadata:
      labels:
        name: redis-slot1   
    spec:
      containers:
      - name: redis-slot1
        image: docker.io/versates/redis-cluster:3.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis
          name: redis-slot1-volume
      volumes:
      - name: redis-slot1-volume
        hostPath:
          path: /root/redisv 
